"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000
add_newline = true

format = """
[ $os ](fg:#808080 bg:#303030)\
$directory\
$git_branch\
$git_commit\
$git_status\
$cmd_duration\
[](fg:#303030) 
"""

right_format = """
$direnv\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_state\
$git_metrics\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$jobs\
$status\
$container\
$battery\
$time\
"""

[battery]
disabled = false
format = "[$symbol$percentage]($style) "

[character]
disabled = false
format = "[ $symbol ](fg:#808080 bg:#303030)"
success_symbol = "[󰄬](bold green bg:#303030)"
error_symbol = "[✗](red bg:#303030)"

[cmd_duration]
format = "[ [$duration](fg:#a0a9cb bg:#303030) ]($style)"
style = "fg:#808080 bg:#303030"
show_milliseconds = true
min_time = 0

[os]
disabled = false
style = "fg:#808080 bg:#303030"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
disabled = false
style = "fg:#01ABF9 bg:#303030"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"repository" = ""

[git_branch]
disabled = false
symbol = ""
style = "fg:#808080 bg:#303030"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#303030)]($style)'

[git_status]
disabled = false
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#303030)]($style)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[nodejs]
disabled = false
symbol = ""
style = "fg:#808080 bg:#303030"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#303030)]($style)'

[golang]
disabled = false
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#303030)]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#808080 bg:#303030"
format = '[[  $time ](fg:#a0a9cb bg:#303030)]($style)'

[bun]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[$symbol($version)]($style)'

[docker_context]
style = "fg:#a0a9cb bg:#303030"
format = '[$symbol$context]($style)'

[helm]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[$symbol($version)]($style)'

[hg_branch]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[$symbol$branch]($style)'

[kubernetes]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[$symbol$context( \($namespace\))]($style)'

[memory_usage]
disabled = true
style = "fg:#a0a9cb bg:#303030"
format = '$symbol[$ram( | $swap)]($style)'

[nix_shell]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[$symbol$state( \($name\))]($style)'

[ocaml]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[$symbol($version)(\($switch_indicator$switch_name\))]($style)'

[openstack]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[$symbol$cloud(\($project\))]($style)'

[package]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[ $symbol$version]($style)'

[sudo]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[🔒 $symbol]($style)'

[zig]
disabled = false
style = "fg:#a0a9cb bg:#303030"
format = '[$symbol($version)]($style)'
